// Code generated by go-bindata. DO NOT EDIT.
// sources:
// templates/dot.tmpl (752B)
// templates/dot_relations.tmpl (1.02kB)
// templates/dot_tables.tmpl (1.195kB)

package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesDotTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x84\x92\x5d\xcb\xd3\x30\x14\x80\xef\xfb\x2b\x42\xae\xbb\x98\x55\x87\x8a\xcb\xc0\x0b\x85\x81\x6e\xa2\xbb\xf2\x03\x49\x9b\xb3\x36\x9a\x25\x25\x39\x63\x60\xe8\x7f\x97\xb6\x1b\x4d\xe7\xf0\xed\x45\x39\x3c\xe7\x23\x4f\x4f\x13\xe3\x82\x28\x38\x6a\x0b\x84\x2a\x87\x94\x2c\xba\x2e\xab\xbd\x6c\x1b\x12\x33\x42\x08\x19\xe3\x6f\x43\xdc\x3f\x7d\x83\x3e\x12\x76\xd0\x68\x60\x7c\xbf\x45\xf4\xba\x3c\x23\x04\x66\x64\x09\x66\x98\x71\xab\x1f\x88\x58\xaf\xdf\xef\x77\x07\xf2\x69\xbf\xdd\x1d\x16\x5f\xb6\x5f\xdf\x09\x5a\x70\xba\x89\xf1\x7f\x73\xba\x6e\xfd\xac\x6f\xdb\x6c\xf2\xf9\xb8\x5f\xe7\x80\xc2\xdc\x41\xe3\x2a\x81\xf9\xcc\x13\xac\x9a\xb9\x58\xa7\x20\x40\x2b\x38\x5b\x4d\x85\x5e\xda\xdf\xff\xc0\x56\x2a\x41\x39\x2b\x72\xce\x0a\x3a\xe1\x93\xf4\xb5\xb6\x7d\x86\x27\xb4\x02\x5b\x81\x45\x2f\x11\x04\xfa\x33\x4c\x99\xd0\x1a\x6d\x21\x08\x3a\x06\x74\x7e\xaa\xd2\x5e\x7c\xf8\x3c\xa0\x1f\x6f\xb2\x9b\x60\xb2\xeb\x71\x77\xf4\xfb\x2e\x69\x3c\x3a\x8b\x41\xff\x01\xb1\x7c\xf1\xd0\xeb\x65\xce\x19\x5f\x25\x0d\x2d\xd8\x8b\x56\xd8\x88\x25\xe3\x89\x59\x23\x5b\x10\x1f\x3d\x54\xce\xab\x54\x01\x54\x9d\x2a\xf4\x8e\xa5\xc3\xe6\x91\x40\x31\x41\xe9\xbd\xbb\x0c\x94\xb3\xd7\x4f\x9d\x3d\x7c\x96\xb4\xb5\x01\xf1\xbc\xb8\xc3\x4a\x07\x94\xb6\x02\xb1\x64\xaf\x52\xad\x18\x11\x4e\xad\x91\x38\xde\xd3\x9f\x1e\x8c\x44\xed\x6c\xa0\x84\x5d\xff\xf0\x7d\x09\xca\xd2\xc0\x35\xdf\x65\x31\x82\x55\x5d\xf7\x37\x00\x00\xff\xff\xec\x09\x89\xb9\xf0\x02\x00\x00")

func templatesDotTmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesDotTmpl,
		"templates/dot.tmpl",
	)
}

func templatesDotTmpl() (*asset, error) {
	bytes, err := templatesDotTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/dot.tmpl", size: 752, mode: os.FileMode(0664), modTime: time.Unix(1595332708, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x82, 0x6f, 0x6d, 0x33, 0xa, 0x4f, 0x57, 0xe4, 0x65, 0xb4, 0xbb, 0xf4, 0xd9, 0xc1, 0x34, 0x16, 0xdc, 0x69, 0x7d, 0x32, 0x9, 0x7d, 0x46, 0xe9, 0x11, 0x7b, 0x46, 0x5a, 0x90, 0xd3, 0x7e, 0x63}}
	return a, nil
}

var _templatesDot_relationsTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x92\x41\x4b\xc3\x30\x14\x80\xef\xfd\x15\x8f\x9e\x9c\xb6\x75\x3d\xdb\x6d\x88\xe0\x49\x2a\x8c\xdd\x44\xe4\xd5\xbe\x6e\x81\x98\x60\x1a\x19\x12\xf2\xdf\x25\x75\xc6\x6d\x69\x8b\xf5\xf6\x78\xa4\xdf\x17\xf2\xd5\x98\x9a\x1a\x26\x08\xe2\x5a\xea\x17\x45\x1c\x35\x93\xa2\x8d\xad\x8d\x8c\x51\x28\xb6\x04\xd9\xfa\x67\x6b\x6d\x04\x60\x4c\xf6\x40\x8d\xde\x60\xc5\xa9\xc4\x37\xb2\x16\xd2\xd4\x6d\xd7\x6c\xbb\x3b\x59\x3f\x45\x00\xee\x7c\x0a\xac\x81\x0b\x7a\x87\xef\x23\x77\xa8\x6a\x26\x90\x33\xfd\x09\xf1\x65\x3c\x83\xb4\xe3\x02\xa0\x52\x72\xbf\x23\xac\x17\xf2\x55\xc9\x7d\xe2\x46\x8e\x15\xf1\x45\x51\xdc\x3f\x96\x9b\xe5\x3c\xcb\xca\xe2\xba\x1b\x97\x89\x87\x13\x6f\x69\xc4\x70\x15\xcf\xfa\xf9\x9a\x28\x54\xe4\xff\x51\xac\x26\x29\xcc\x3c\xc9\xed\x80\x23\x7c\x0a\x21\x05\xc9\x7e\x8e\x09\xae\x62\xfb\xb8\xa2\xf6\xd8\x43\x0b\x5f\xf4\x56\x6b\xc5\xaa\x0f\x4d\x6d\xd6\xa1\xfd\xc1\x40\x34\xf0\xc1\x1f\x85\xdd\xbb\xb9\xbf\x66\xbc\xbd\x46\xc6\x0f\xed\xdd\x38\xd8\xbe\xbf\x4b\xc0\x3f\x2b\xff\x4b\x77\xcf\x19\x08\xf2\xe9\x82\xd5\x24\xc1\x49\xf7\x91\xec\x1d\xc6\x67\x0f\x31\xe6\xfc\x22\xb6\x87\xea\x1b\x3c\xdf\x44\xc7\x8b\xe3\xf9\x2b\x00\x00\xff\xff\xac\x06\x1a\x24\xfc\x03\x00\x00")

func templatesDot_relationsTmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesDot_relationsTmpl,
		"templates/dot_relations.tmpl",
	)
}

func templatesDot_relationsTmpl() (*asset, error) {
	bytes, err := templatesDot_relationsTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/dot_relations.tmpl", size: 1020, mode: os.FileMode(0664), modTime: time.Unix(1612205732, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x1c, 0x48, 0xa3, 0xa7, 0x23, 0xda, 0x22, 0x95, 0x1c, 0xdf, 0xc3, 0x2e, 0x9e, 0xa, 0x70, 0xfd, 0x51, 0xfb, 0x2c, 0xc6, 0x32, 0xd0, 0x5b, 0x12, 0x21, 0x2a, 0x47, 0x89, 0x1d, 0x61, 0x15, 0x25}}
	return a, nil
}

var _templatesDot_tablesTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xa4\x52\x5d\x8f\x93\x40\x14\x7d\xef\xaf\xb8\xb9\xd9\xf8\xd4\x96\xae\x56\x1f\x5c\x86\x84\xaf\xee\x92\x20\x34\xec\x44\x13\x8d\x31\x50\xa6\x0d\x71\x16\x0c\xcc\x9a\x6c\x46\xfe\xbb\x61\x3a\x60\x41\xfc\x8a\x7d\x29\xf7\x70\x3f\x0e\xe7\x1c\x29\x73\x76\x2c\x4a\x06\x98\x57\xe2\x93\x48\x33\xce\x1a\x6c\xdb\x85\x94\x75\x5a\x9e\x18\x5c\x89\xcf\x4b\xb8\x12\xf0\x9a\xc0\x9a\xaa\xb7\x6d\xbb\x00\x90\x72\x1d\xa5\x0f\xac\x6d\xe1\x03\x4f\x33\xc6\x89\x69\x52\xdb\x09\xfd\x05\xa8\x9f\x13\x27\x9e\x9f\x10\xdc\xa0\x06\x5c\x3f\x0c\xf7\xb6\xe7\x05\xd1\xed\x04\xbd\xdf\xdb\xee\x19\x5d\xbf\xec\xf1\x77\x81\x47\xef\x08\x5e\xbf\xd8\xf6\x88\x1d\x06\xb7\x11\x41\xd7\x8f\xa8\x9f\xf4\xa0\xa5\xff\x4d\x9a\xf4\x8f\x5d\xe1\x4d\xba\xe1\xad\xae\x9d\x98\xd2\xf8\x0d\x5e\xae\xff\x31\x07\x60\xee\xe2\x88\xc2\x3e\x0e\x22\xba\xba\x0f\xde\xfb\x04\xaf\xb7\x08\x3b\xdb\xf5\x09\xde\x31\xfe\x95\x89\xe2\x90\x42\x56\xf1\x1c\x2d\xd3\xb1\xa4\x5c\xd3\x42\x70\xd6\xb6\xa6\xe1\x58\xa6\xd1\x4d\x5f\xae\x93\x72\x05\xc5\x51\xab\x66\x0b\x51\x17\xd9\xa3\x60\xcd\x5a\xe9\x05\x2b\x25\xe3\xf4\xf8\xf9\x98\x5d\x17\x29\x87\x40\xa4\xbc\x38\xe0\x98\xd0\x06\xc1\x8d\xc3\x38\x21\x78\xaa\xd9\xd3\xab\x0d\x5a\xcf\xca\xac\xf9\x72\xd3\x91\x99\xbb\xd3\x91\x9b\x23\xc6\xca\x7c\x44\xc1\x34\xa8\x37\xc8\x69\xf4\x7a\x9a\x86\x32\xf5\x5c\xf4\xdf\xe3\x56\xfc\xf1\xa1\x6c\x86\xf1\x6f\xe7\xd6\xdf\xda\xaf\x0d\x08\xfd\x1d\xfd\x87\x44\x6c\x67\xf2\xd0\x93\xec\xd8\xe8\x84\x76\x01\x3d\xa8\x80\x6a\x6a\xc3\x77\xfd\x2a\x18\x8a\x87\x35\xe3\xf7\x73\x1c\xd9\x3a\x56\x6e\x2c\xc0\x1f\x1c\xfd\x7f\x3f\xe7\xcf\xcc\xd3\xfa\x3b\x3b\x87\x5e\xdd\xf9\x93\xbd\x7a\xcd\xd8\xef\x69\xae\xb2\xd3\xa1\xe2\x55\xad\x77\x2c\x8f\x05\xe7\x0a\x20\x38\x13\xc2\xa1\x19\x97\xaa\xbd\x11\x4f\x9c\x91\x6e\x86\xe5\xd3\xb3\xaa\xfe\x78\xb3\xb8\x84\x2e\x9f\xbf\x07\x00\x00\xff\xff\x3c\x8a\xab\x86\xab\x04\x00\x00")

func templatesDot_tablesTmplBytes() ([]byte, error) {
	return bindataRead(
		_templatesDot_tablesTmpl,
		"templates/dot_tables.tmpl",
	)
}

func templatesDot_tablesTmpl() (*asset, error) {
	bytes, err := templatesDot_tablesTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/dot_tables.tmpl", size: 1195, mode: os.FileMode(0664), modTime: time.Unix(1612249805, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa0, 0xfb, 0x63, 0x46, 0x83, 0x6b, 0x2c, 0xfe, 0x10, 0x5, 0xa0, 0xcc, 0xe2, 0x41, 0xe7, 0xcc, 0x43, 0x75, 0xcd, 0xeb, 0x89, 0xd3, 0x5e, 0x1, 0xdc, 0xd8, 0xe0, 0x4b, 0x60, 0x74, 0x3c, 0xc4}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/dot.tmpl":           templatesDotTmpl,
	"templates/dot_relations.tmpl": templatesDot_relationsTmpl,
	"templates/dot_tables.tmpl":    templatesDot_tablesTmpl,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"templates": {nil, map[string]*bintree{
		"dot.tmpl": {templatesDotTmpl, map[string]*bintree{}},
		"dot_relations.tmpl": {templatesDot_relationsTmpl, map[string]*bintree{}},
		"dot_tables.tmpl": {templatesDot_tablesTmpl, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
